## Tugas
- Selesaikan soal-soal berikut dengan membuat program masing-masing soal sesuai yang ditanyakan.
- Kerjakan dengan membuat cell code baru di bawah setiap soal
- Upload file .ipynb yang telah berisi jawaban lengkap pada Akun Github dengan membuat Repository baru


1. Tentukan determinan matriks berikut:

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right)
$$

In [12]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 2], [3, 4]])

# Menghitung determinan matriks
determinant = np.linalg.det(M)

print("Nilai Determinan :")
print(determinant)

Nilai Determinan :
-2.0000000000000004


2. Tentukan invers Matriks Berikut:

$$\displaystyle B = \left( \begin{array}{cc}
10 & -22 \\
3 & 45
\end{array} 
\right)
$$

In [10]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[10, -22], [3, 45]])

# Menghitung invers matriks
inverse_of_M = np.linalg.inv(M)

print("Invers :")
print(inverse_of_M)

Invers :
[[ 0.0872093   0.04263566]
 [-0.00581395  0.01937984]]


3. Tentukan apakah matriks berikut berkondisi buruk:
$$\displaystyle C = \left( \begin{array}{cc}
1 & 10^{-10} \\
10^{-10} & 1
\end{array} 
\right)
$$

In [8]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 10^-10], [10^-10, 1]])

# Menghitung determinan matriks
determinant = np.linalg.det(M)

print("Nilai Determinan :")
print(determinant)

Nilai Determinan :
-15.0


In [4]:
from numpy.linalg import \
             cond, matrix_rank

A = np.array([[1,10^-10],
              [10^-10,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Condition number:
 1.6666666666666667
Rank:
 2
Augmented matrix:
 [[ 1 -4  1]
 [-4  1  2]]


Matriks diatas termasuk kedalam matriks yang berkondisi buruk, karena nilai determinannya mendekati atau kurang dari 0 dan condition number atau angka kondisinya menunjukkan angka yang cukup tinggi sehingga matriks semakin dekat dengan singular.

4. Tentukan apakah sistem persamaan linier berikut memiliki solusi. Jika ada, bagaimana solusinya?

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right) $$


$$\displaystyle
b =  \left( \begin{array}{cc}
5 & 6 
\end{array} 
\right) \\
$$

In [6]:
import numpy as np

# Matriks koefisien
A = np.array([[1, 2],
              [3, 4]])

# Vektor hasil
B = np.array([5, 6])

# Menghitung invers matriks koefisien
A_inv = np.linalg.inv(A)

# Menyelesaikan sistem persamaan linear
X = np.dot(A_inv, B)

# Menampilkan hasil
print("Solusi dari sistem persamaan linear:")
print("x =", X[0])
print("y =", X[1])


Solusi dari sistem persamaan linear:
x = -3.9999999999999996
y = 4.5


5. Tentukan dimensi ruang nol matriks berikut:


$$\displaystyle
C =
\left(
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right)
$$

In [7]:
import numpy as np


C = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Reduksi baris
reduced_row_echelon_form, pivot_columns = np.linalg.qr(C, mode='complete')

# Hitung dimensi ruang nol
num_columns = C.shape[1]
num_pivot_columns = len(pivot_columns)
dimension_null_space = num_columns - num_pivot_columns

print("Matriks dalam bentuk reduksi baris:")
print(reduced_row_echelon_form)
print("\nKolom pivot:")
print(pivot_columns)
print("\nDimensi ruang nol:", dimension_null_space)


Matriks dalam bentuk reduksi baris:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

Kolom pivot:
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]

Dimensi ruang nol: 0
